### PR TITLE
Accept null as a value for an optional

### PR DESCRIPTION
**Pull request by santeri**

### CODE REVIEW

**Comment by santeri** [comment]
@fxb

**Comment by punchfox** [comment]
This is already supported, but with composing instead of directly in the `optional_t` codec. See https://github.com/spotify/spotify-json/blob/master/doc/api.md#handling-missing-empty-null-and-invalid-values.

**Comment by punchfox** [comment]
An old version of optional used to do this, but it was inconsistent with our smart pointer codecs, so we removed it. The codecs always require a valid value in the JSON file, i.e., an optional string must either not be there or a valid string. To handle `null` or any other special value, use the `one_of_t` codec.

**Comment by santeri** [comment]
Ok, though as a user I'd assume that null was a valid value for an optional.

Principle of least astonishment and all that, you know..

**Pull request closed without merging**
